version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env.docker
    volumes:
      - .:/var/www/html
      - .env.docker:/var/www/html/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: app_password
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./.docker/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db_data:
